if(MSVC)
    add_compile_options(/W4 /permissive-)
else()
    add_compile_options(-Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
endif()

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    add_definitions(-DDEBUG)
    if(NOT MSVC)
        add_compile_options(-g -O0)
    endif()
else()
    add_definitions(-DNDEBUG)
    if(NOT MSVC)
        add_compile_options(-O3)
    endif()
endif()
